
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app  # Bind mount for frontend code

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app  # Bind mount for middleware code

  backend:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "5191:5191"
    volumes:
      - ./web:/app  # Bind mount for backend code
