version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  middleware:
    build:
      context: ./middleware
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
