
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  middleware:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  backend:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
