FROM node:20

RUN apt-get -y install git \
    && git clone https://github.com/flakesofcorn/web_app_thingy.git

WORKDIR /WEB_APP_THINGY/frontend/

RUN npm i

EXPOSE 3000

CMD [npm, start]

# CMD cd ..
# CMD cd web

# CMD dotnet run